"""Generate yir26-carousel-rig.jsx (After Effects build script) from rig.py.

In AE: File > Scripts > Run Script File... > yir26-carousel-rig.jsx, then save
the project as yir26-carousel.aep. It builds:
  _CONTROLS                 null CONTROLS with FIELD / BOOK_BASE / BOOK_ACCENT
  yir26-carousel-ebook      560x400 @24fps, 3.75 s
  yir26-carousel-audio      same strip, timing and landing; square covers + player row
Brand swap = change the three colour controls (values in the CONTROLS layer comment).
"""
import json
from pathlib import Path

import rig

HERE = Path(__file__).parent
f2 = lambda h: [round(v / 255, 4) for v in rig.rgb(h)]

DATA = {
    "W": rig.W, "H": rig.H, "FPS": rig.FPS, "DUR": rig.TOTAL_S,
    "T0": rig.HOLD_IN_F / rig.FPS, "T1": (rig.HOLD_IN_F + rig.MOTION_F) / rig.FPS,
    "EASE_OUT_INFL": rig.EASE[0] * 100, "EASE_IN_INFL": (1 - rig.EASE[2]) * 100,
    "X_LAND": rig.X_LAND, "STRIP_LEN": rig.STRIP_LEN, "PITCH": rig.PITCH,
    "SLOTS": rig.SLOTS, "ROLES": {str(s): rig.role(s) for s in rig.SLOTS},
    "N": rig.N_COVERS, "COVER_R": rig.COVER_R, "BAND_TOP": rig.BAND_TOP, "BAND_H": rig.BAND_H,
    "BAND_SHADE": rig.BAND_SHADE, "EINK_LO": rig.EINK_LO,
    "GHOSTS": [list(g) for g in rig.GHOSTS], "GHOST_FULL": rig.GHOST_FULL_SPEED,
    "DEVICE": rig.DEVICE, "SCREEN": rig.SCREEN, "VARIANTS": rig.VARIANTS,
    "PROGRESS": rig.PROGRESS, "PLAY": rig.PLAY, "WAVE": rig.WAVE, "WAVE_T0": round(rig.landed_time(), 4),
    "C": {"WHITE": f2(rig.WHITE), "BEZEL": f2(rig.BEZEL), "PAPER": f2(rig.PAPER),
          "INK_DARK": f2(rig.INK_DARK), "INK_LIGHT": f2(rig.INK_LIGHT), "TRACK": f2(rig.TRACK)},
    "BRANDS": {b: {k: f2(v) for k, v in c.items()} for b, c in rig.BRANDS.items()},
    "BRAND_HEX": rig.BRANDS,
}

JSX = r"""// YIR 2026 cover carousel: shared AE rig. Generated by ae_rig.py from rig.py (do not hand-edit numbers).
// Run: File > Scripts > Run Script File. Then save as yir26-carousel.aep.
(function () {
var D = __DATA__;
app.beginUndoGroup("YIR26 cover carousel rig");
var proj = app.project ? app.project : app.newProject();
var folder = proj.items.addFolder("YIR26 cover carousel");

var CTRL_REF = 'comp("_CONTROLS").layer("CONTROLS").effect("';
function colourExpr(key, shade, eink) {
    var src = (key === "WHITE") ? "[1,1,1,1]" : CTRL_REF + key + '")("Color")';
    var e = "var c = " + src + "; var k = " + shade + ";\n";
    if (!eink) return e + "[c[0]*k, c[1]*k, c[2]*k, 1]";
    var lo = D.C.INK_DARK, hi = D.C.INK_LIGHT;
    return e + "var l = 0.299*c[0]*k + 0.587*c[1]*k + 0.114*c[2]*k;\n" +
        "var t = clamp((l - " + D.EINK_LO + ") / " + (1 - D.EINK_LO) + ", 0, 1);\n" +
        "[" + lo[0] + "+(" + (hi[0] - lo[0]) + ")*t, " + lo[1] + "+(" + (hi[1] - lo[1]) + ")*t, " +
        lo[2] + "+(" + (hi[2] - lo[2]) + ")*t, 1]";
}

function setXf(layer, anchor, pos) {
    var xf = layer.property("ADBE Transform Group");
    xf.property("ADBE Anchor Point").setValue(anchor);
    xf.property("ADBE Position").setValue(pos);
}
function shapeLayer(comp, name) {
    var L = comp.layers.addShape();
    L.name = name;
    setXf(L, [0, 0], [0, 0]);
    return L;
}
function root(layer) { return layer.property("ADBE Root Vectors Group"); }
// Adds a group holding one rect + fill to `contents` (a "Contents" property group).
function rectGroup(contents, name, x, y, w, h, r, rgb, expr) {
    var g = contents.addProperty("ADBE Vector Group");
    g.name = name;
    var gc = contents.property(name).property("ADBE Vectors Group");
    var rect = gc.addProperty("ADBE Vector Shape - Rect");
    rect.property("ADBE Vector Rect Size").setValue([w, h]);
    rect.property("ADBE Vector Rect Position").setValue([x + w / 2, y + h / 2]);
    rect.property("ADBE Vector Rect Roundness").setValue(r);
    gc = contents.property(name).property("ADBE Vectors Group");
    var fill = gc.addProperty("ADBE Vector Graphic - Fill");
    var col = fill.property("ADBE Vector Fill Color");
    col.setValue(rgb.length === 3 ? [rgb[0], rgb[1], rgb[2], 1] : rgb);
    if (expr) col.expression = expr;
    return contents.property(name);
}
function addColorControl(layer, name, rgb) {
    var fx = layer.property("ADBE Effect Parade").addProperty("ADBE Color Control");
    fx.name = name;
    layer.property("ADBE Effect Parade").property(name).property("ADBE Color Control-0001")
        .setValue([rgb[0], rgb[1], rgb[2], 1]);
}

// ---- _CONTROLS: the single colour control -------------------------------------
var ctrlComp = proj.items.addComp("_CONTROLS", D.W, D.H, 1, D.DUR, D.FPS);
ctrlComp.parentFolder = folder;
var CONTROLS = ctrlComp.layers.addNull();
CONTROLS.name = "CONTROLS";
addColorControl(CONTROLS, "FIELD", D.BRANDS.kplus.FIELD);
addColorControl(CONTROLS, "BOOK_BASE", D.BRANDS.kplus.BOOK_BASE);
addColorControl(CONTROLS, "BOOK_ACCENT", D.BRANDS.kplus.BOOK_ACCENT);
CONTROLS.comment = "Brand swap = these three colours only. K+: FIELD " + D.BRAND_HEX.kplus.FIELD +
    ", BOOK_BASE " + D.BRAND_HEX.kplus.BOOK_BASE + ", BOOK_ACCENT " + D.BRAND_HEX.kplus.BOOK_ACCENT +
    " | ALC: FIELD " + D.BRAND_HEX.alc.FIELD + ", BOOK_BASE " + D.BRAND_HEX.alc.BOOK_BASE +
    ", BOOK_ACCENT " + D.BRAND_HEX.alc.BOOK_ACCENT;

function stripLayer(comp, name, size, eink) {
    var L = shapeLayer(comp, name);
    var w = size[0], h = size[1];
    for (var i = 0; i < D.SLOTS.length; i++) {
        var slot = D.SLOTS[i], role = D.ROLES[String(slot)];
        var gname = "cover_" + slot + "_" + role;
        var g = root(L).addProperty("ADBE Vector Group");
        g.name = gname;
        var gc = root(L).property(gname).property("ADBE Vectors Group");
        var x = slot * D.PITCH - w / 2, y = -h / 2;
        // band first = drawn on top of the body
        rectGroup(gc, "title_band", x, y + h * D.BAND_TOP, w, h * D.BAND_H, 0, [1, 1, 1],
                  colourExpr(role, D.BAND_SHADE, eink));
        gc = root(L).property(gname).property("ADBE Vectors Group");
        rectGroup(gc, "body", x, y, w, h, D.COVER_R, [1, 1, 1], colourExpr(role, 1, eink));
    }
    return L;
}

function build(variant) {
    var V = D.VARIANTS[variant], S = D.SCREEN, DV = D.DEVICE;
    var comp = proj.items.addComp("yir26-carousel-" + variant, D.W, D.H, 1, D.DUR, D.FPS);
    comp.parentFolder = folder;

    var field = shapeLayer(comp, "FIELD");
    rectGroup(root(field), "field", 0, 0, D.W, D.H, 0, [0, 0, 0], CTRL_REF + 'FIELD")("Color")');

    var strip = stripLayer(comp, "STRIP", V.cover, false);
    var ctrl = comp.layers.addNull();
    ctrl.name = "STRIP_CTRL";
    ctrl.moveBefore(strip);
    setXf(ctrl, [0, 0], [D.X_LAND, V.strip_y]);
    var pos = ctrl.property("ADBE Transform Group").property("ADBE Position");
    pos.dimensionsSeparated = true;
    var px = ctrl.property("ADBE Transform Group").property("ADBE Position_0");
    px.setValueAtTime(D.T0, D.X_LAND);
    px.setValueAtTime(D.T1, D.X_LAND - D.STRIP_LEN);
    for (var k = 1; k <= 2; k++) {
        px.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
    }
    // single ease: fast start (out speed = 4x average, 25 %), hard stop (0, 70 %), no overshoot
    var avg = -D.STRIP_LEN / (D.T1 - D.T0);
    px.setTemporalEaseAtKey(1, [new KeyframeEase(0, 33.33)], [new KeyframeEase(avg * 100 / D.EASE_OUT_INFL, D.EASE_OUT_INFL)]);
    px.setTemporalEaseAtKey(2, [new KeyframeEase(0, D.EASE_IN_INFL)], [new KeyframeEase(0, 33.33)]);
    strip.parent = ctrl;
    setXf(strip, [0, 0], [0, 0]);
    for (var g = D.GHOSTS.length - 1; g >= 0; g--) {
        var back = D.GHOSTS[g][0], alpha = D.GHOSTS[g][1] * 100;
        var ghost = strip.duplicate();
        ghost.name = "STRIP_GHOST_" + back;
        ghost.moveAfter(strip);
        ghost.parent = null;   // ghosts follow STRIP_CTRL by expression, 1-2 frames late
        var gx = ghost.property("ADBE Transform Group");
        gx.property("ADBE Position").expression =
            'var c = thisComp.layer("STRIP_CTRL").transform, t = time - ' + back + ' * thisComp.frameDuration;\n' +
            '[c.xPosition.valueAtTime(t), c.yPosition.valueAtTime(t)]';
        gx.property("ADBE Opacity").expression =
            'var x = thisComp.layer("STRIP_CTRL").transform.xPosition, f = thisComp.frameDuration;\n' +
            'var v = Math.abs(x.valueAtTime(time) - x.valueAtTime(time - f));\n' +
            alpha + ' * clamp(v / ' + D.GHOST_FULL + ', 0, 1)';
    }


    var bezel = shapeLayer(comp, "DEVICE_BEZEL");
    rectGroup(root(bezel), "bezel", DV.x, DV.y, DV.w, DV.h, DV.r, D.C.BEZEL);
    var paper = shapeLayer(comp, "SCREEN_PAPER");
    rectGroup(root(paper), "paper", S.x, S.y, S.w, S.h, S.r, D.C.PAPER);

    var eink = stripLayer(comp, "EINK_STRIP", V.cover, true);
    eink.parent = ctrl;
    setXf(eink, [0, 0], [0, 0]);
    var matte = shapeLayer(comp, "SCREEN_MATTE");
    rectGroup(root(matte), "matte", S.x, S.y, S.w, S.h, S.r, [1, 1, 1]);
    if (typeof eink.setTrackMatte === "function") {
        eink.setTrackMatte(matte, TrackMatteType.ALPHA);
    } else {
        eink.trackMatteType = TrackMatteType.ALPHA;   // legacy: uses the layer directly above
    }
    matte.enabled = false;

    if (variant === "audio") {
        var P = D.PROGRESS, G = D.PLAY, WV = D.WAVE;
        var prog = shapeLayer(comp, "PROGRESS");
        rectGroup(root(prog), "fill", P.x, P.y, P.w * P.fill, P.h, P.h / 2, D.C.INK_DARK);
        rectGroup(root(prog), "track", P.x, P.y, P.w, P.h, P.h / 2, D.C.TRACK);
        var play = shapeLayer(comp, "PLAY");
        var pg = root(play).addProperty("ADBE Vector Group");
        pg.name = "play";
        var pc = root(play).property("play").property("ADBE Vectors Group");
        var path = pc.addProperty("ADBE Vector Shape - Group");
        var tri = new Shape();
        tri.vertices = [[G.x, G.cy - G.h / 2], [G.x + G.w, G.cy], [G.x, G.cy + G.h / 2]];
        tri.closed = true;
        path.property("ADBE Vector Shape").setValue(tri);
        pc = root(play).property("play").property("ADBE Vectors Group");
        pc.addProperty("ADBE Vector Graphic - Fill").property("ADBE Vector Fill Color")
            .setValue([D.C.INK_DARK[0], D.C.INK_DARK[1], D.C.INK_DARK[2], 1]);
        var wave = shapeLayer(comp, "WAVEFORM");
        for (var j = 0; j < WV.peaks.length; j++) {
            var bx = WV.x + j * (WV.bar_w + WV.gap);
            var bar = rectGroup(root(wave), "bar_" + (j + 1), bx, WV.cy - WV.rest / 2, WV.bar_w, WV.rest,
                                WV.bar_w / 2, D.C.INK_DARK);
            // one beat after landing, then back to rest (only extra motion; ends well before 5 s)
            root(wave).property("bar_" + (j + 1)).property("ADBE Vectors Group").property(1)
                .property("ADBE Vector Rect Size").expression =
                "var u = (time - " + D.WAVE_T0 + " - " + (j * WV.stagger) + ") / " + WV.dur + ";\n" +
                "var b = (u > 0 && u < 1) ? Math.sin(Math.PI * u) : 0;\n" +
                "[" + WV.bar_w + ", " + WV.rest + " + " + (WV.peaks[j] - WV.rest) + " * b]";
        }
    }
    return comp;
}

var ebook = build("ebook");
build("audio");
ebook.openInViewer();
app.endUndoGroup();
alert("YIR26 carousel rig built: _CONTROLS, yir26-carousel-ebook, yir26-carousel-audio.\n" +
      "Brand swap = the three colour controls on _CONTROLS > CONTROLS.\nSave as yir26-carousel.aep.");
})();
"""

out = HERE / "yir26-carousel-rig.jsx"
out.write_text(JSX.replace("__DATA__", json.dumps(DATA)))
print(out.name, out.stat().st_size, "bytes")
