// YIR 2026 cover carousel: shared AE rig. Generated by ae_rig.py from rig.py (do not hand-edit numbers).
// Run: File > Scripts > Run Script File. Then save as yir26-carousel.aep.
(function () {
var D = {"W": 560, "H": 400, "FPS": 24, "DUR": 3.75, "T0": 0.20833333333333334, "T1": 2.7083333333333335, "EASE_OUT_INFL": 25.0, "EASE_IN_INFL": 70.0, "X_LAND": 280.0, "STRIP_LEN": 1232, "PITCH": 176, "SLOTS": [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "ROLES": {"-3": "BOOK_BASE", "-2": "WHITE", "-1": "BOOK_BASE", "0": "BOOK_ACCENT", "1": "WHITE", "2": "BOOK_BASE", "3": "WHITE", "4": "BOOK_BASE", "5": "WHITE", "6": "BOOK_BASE", "7": "BOOK_ACCENT", "8": "WHITE", "9": "BOOK_BASE", "10": "WHITE"}, "N": 7, "COVER_R": 3, "BAND_TOP": 0.16, "BAND_H": 0.14, "BAND_SHADE": 0.82, "EINK_LO": 0.55, "GHOSTS": [[1, 0.45], [2, 0.2]], "GHOST_FULL": 30, "DEVICE": {"x": 190, "y": 71, "w": 180, "h": 258, "r": 18}, "SCREEN": {"x": 204, "y": 87, "w": 152, "h": 216, "r": 3}, "VARIANTS": {"ebook": {"cover": [124, 186], "strip_y": 195}, "audio": {"cover": [120, 120], "strip_y": 163}}, "PROGRESS": {"x": 220, "y": 239, "w": 120, "h": 4, "fill": 0.38}, "PLAY": {"x": 253, "cy": 268, "w": 16, "h": 18}, "WAVE": {"x": 279, "cy": 268, "bar_w": 4, "gap": 4, "rest": 4, "peaks": [12, 20, 14, 9], "dur": 0.4, "stagger": 0.05}, "WAVE_T0": 2.3458, "C": {"WHITE": [1.0, 1.0, 1.0], "BEZEL": [0.1059, 0.1059, 0.1059], "PAPER": [0.8549, 0.8549, 0.8353], "INK_DARK": [0.2275, 0.2275, 0.2196], "INK_LIGHT": [0.9569, 0.9569, 0.9412], "TRACK": [0.7059, 0.7059, 0.6902]}, "BRANDS": {"kplus": {"FIELD": [0.0392, 0.349, 0.7765], "BOOK_BASE": [0.8, 0.8627, 0.9529], "BOOK_ACCENT": [0.9451, 0.7725, 0.2549]}, "alc": {"FIELD": [0.749, 0.0, 0.0], "BOOK_BASE": [0.949, 0.7961, 0.8], "BOOK_ACCENT": [0.898, 0.6, 0.6039]}}, "BRAND_HEX": {"kplus": {"FIELD": "#0A59C6", "BOOK_BASE": "#CCDCF3", "BOOK_ACCENT": "#F1C541"}, "alc": {"FIELD": "#BF0000", "BOOK_BASE": "#F2CBCC", "BOOK_ACCENT": "#E5999A"}}};
app.beginUndoGroup("YIR26 cover carousel rig");
var proj = app.project ? app.project : app.newProject();
var folder = proj.items.addFolder("YIR26 cover carousel");

var CTRL_REF = 'comp("_CONTROLS").layer("CONTROLS").effect("';
function colourExpr(key, shade, eink) {
    var src = (key === "WHITE") ? "[1,1,1,1]" : CTRL_REF + key + '")("Color")';
    var e = "var c = " + src + "; var k = " + shade + ";\n";
    if (!eink) return e + "[c[0]*k, c[1]*k, c[2]*k, 1]";
    var lo = D.C.INK_DARK, hi = D.C.INK_LIGHT;
    return e + "var l = 0.299*c[0]*k + 0.587*c[1]*k + 0.114*c[2]*k;\n" +
        "var t = clamp((l - " + D.EINK_LO + ") / " + (1 - D.EINK_LO) + ", 0, 1);\n" +
        "[" + lo[0] + "+(" + (hi[0] - lo[0]) + ")*t, " + lo[1] + "+(" + (hi[1] - lo[1]) + ")*t, " +
        lo[2] + "+(" + (hi[2] - lo[2]) + ")*t, 1]";
}

function setXf(layer, anchor, pos) {
    var xf = layer.property("ADBE Transform Group");
    xf.property("ADBE Anchor Point").setValue(anchor);
    xf.property("ADBE Position").setValue(pos);
}
function shapeLayer(comp, name) {
    var L = comp.layers.addShape();
    L.name = name;
    setXf(L, [0, 0], [0, 0]);
    return L;
}
function root(layer) { return layer.property("ADBE Root Vectors Group"); }
// Adds a group holding one rect + fill to `contents` (a "Contents" property group).
function rectGroup(contents, name, x, y, w, h, r, rgb, expr) {
    var g = contents.addProperty("ADBE Vector Group");
    g.name = name;
    var gc = contents.property(name).property("ADBE Vectors Group");
    var rect = gc.addProperty("ADBE Vector Shape - Rect");
    rect.property("ADBE Vector Rect Size").setValue([w, h]);
    rect.property("ADBE Vector Rect Position").setValue([x + w / 2, y + h / 2]);
    rect.property("ADBE Vector Rect Roundness").setValue(r);
    gc = contents.property(name).property("ADBE Vectors Group");
    var fill = gc.addProperty("ADBE Vector Graphic - Fill");
    var col = fill.property("ADBE Vector Fill Color");
    col.setValue(rgb.length === 3 ? [rgb[0], rgb[1], rgb[2], 1] : rgb);
    if (expr) col.expression = expr;
    return contents.property(name);
}
function addColorControl(layer, name, rgb) {
    var fx = layer.property("ADBE Effect Parade").addProperty("ADBE Color Control");
    fx.name = name;
    layer.property("ADBE Effect Parade").property(name).property("ADBE Color Control-0001")
        .setValue([rgb[0], rgb[1], rgb[2], 1]);
}

// ---- _CONTROLS: the single colour control -------------------------------------
var ctrlComp = proj.items.addComp("_CONTROLS", D.W, D.H, 1, D.DUR, D.FPS);
ctrlComp.parentFolder = folder;
var CONTROLS = ctrlComp.layers.addNull();
CONTROLS.name = "CONTROLS";
addColorControl(CONTROLS, "FIELD", D.BRANDS.kplus.FIELD);
addColorControl(CONTROLS, "BOOK_BASE", D.BRANDS.kplus.BOOK_BASE);
addColorControl(CONTROLS, "BOOK_ACCENT", D.BRANDS.kplus.BOOK_ACCENT);
CONTROLS.comment = "Brand swap = these three colours only. K+: FIELD " + D.BRAND_HEX.kplus.FIELD +
    ", BOOK_BASE " + D.BRAND_HEX.kplus.BOOK_BASE + ", BOOK_ACCENT " + D.BRAND_HEX.kplus.BOOK_ACCENT +
    " | ALC: FIELD " + D.BRAND_HEX.alc.FIELD + ", BOOK_BASE " + D.BRAND_HEX.alc.BOOK_BASE +
    ", BOOK_ACCENT " + D.BRAND_HEX.alc.BOOK_ACCENT;

function stripLayer(comp, name, size, eink) {
    var L = shapeLayer(comp, name);
    var w = size[0], h = size[1];
    for (var i = 0; i < D.SLOTS.length; i++) {
        var slot = D.SLOTS[i], role = D.ROLES[String(slot)];
        var gname = "cover_" + slot + "_" + role;
        var g = root(L).addProperty("ADBE Vector Group");
        g.name = gname;
        var gc = root(L).property(gname).property("ADBE Vectors Group");
        var x = slot * D.PITCH - w / 2, y = -h / 2;
        // band first = drawn on top of the body
        rectGroup(gc, "title_band", x, y + h * D.BAND_TOP, w, h * D.BAND_H, 0, [1, 1, 1],
                  colourExpr(role, D.BAND_SHADE, eink));
        gc = root(L).property(gname).property("ADBE Vectors Group");
        rectGroup(gc, "body", x, y, w, h, D.COVER_R, [1, 1, 1], colourExpr(role, 1, eink));
    }
    return L;
}

function build(variant) {
    var V = D.VARIANTS[variant], S = D.SCREEN, DV = D.DEVICE;
    var comp = proj.items.addComp("yir26-carousel-" + variant, D.W, D.H, 1, D.DUR, D.FPS);
    comp.parentFolder = folder;

    var field = shapeLayer(comp, "FIELD");
    rectGroup(root(field), "field", 0, 0, D.W, D.H, 0, [0, 0, 0], CTRL_REF + 'FIELD")("Color")');

    var strip = stripLayer(comp, "STRIP", V.cover, false);
    var ctrl = comp.layers.addNull();
    ctrl.name = "STRIP_CTRL";
    ctrl.moveBefore(strip);
    setXf(ctrl, [0, 0], [D.X_LAND, V.strip_y]);
    var pos = ctrl.property("ADBE Transform Group").property("ADBE Position");
    pos.dimensionsSeparated = true;
    var px = ctrl.property("ADBE Transform Group").property("ADBE Position_0");
    px.setValueAtTime(D.T0, D.X_LAND);
    px.setValueAtTime(D.T1, D.X_LAND - D.STRIP_LEN);
    for (var k = 1; k <= 2; k++) {
        px.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
    }
    // single ease: fast start (out speed = 4x average, 25 %), hard stop (0, 70 %), no overshoot
    var avg = -D.STRIP_LEN / (D.T1 - D.T0);
    px.setTemporalEaseAtKey(1, [new KeyframeEase(0, 33.33)], [new KeyframeEase(avg * 100 / D.EASE_OUT_INFL, D.EASE_OUT_INFL)]);
    px.setTemporalEaseAtKey(2, [new KeyframeEase(0, D.EASE_IN_INFL)], [new KeyframeEase(0, 33.33)]);
    strip.parent = ctrl;
    setXf(strip, [0, 0], [0, 0]);
    for (var g = D.GHOSTS.length - 1; g >= 0; g--) {
        var back = D.GHOSTS[g][0], alpha = D.GHOSTS[g][1] * 100;
        var ghost = strip.duplicate();
        ghost.name = "STRIP_GHOST_" + back;
        ghost.moveAfter(strip);
        ghost.parent = null;   // ghosts follow STRIP_CTRL by expression, 1-2 frames late
        var gx = ghost.property("ADBE Transform Group");
        gx.property("ADBE Position").expression =
            'var c = thisComp.layer("STRIP_CTRL").transform, t = time - ' + back + ' * thisComp.frameDuration;\n' +
            '[c.xPosition.valueAtTime(t), c.yPosition.valueAtTime(t)]';
        gx.property("ADBE Opacity").expression =
            'var x = thisComp.layer("STRIP_CTRL").transform.xPosition, f = thisComp.frameDuration;\n' +
            'var v = Math.abs(x.valueAtTime(time) - x.valueAtTime(time - f));\n' +
            alpha + ' * clamp(v / ' + D.GHOST_FULL + ', 0, 1)';
    }


    var bezel = shapeLayer(comp, "DEVICE_BEZEL");
    rectGroup(root(bezel), "bezel", DV.x, DV.y, DV.w, DV.h, DV.r, D.C.BEZEL);
    var paper = shapeLayer(comp, "SCREEN_PAPER");
    rectGroup(root(paper), "paper", S.x, S.y, S.w, S.h, S.r, D.C.PAPER);

    var eink = stripLayer(comp, "EINK_STRIP", V.cover, true);
    eink.parent = ctrl;
    setXf(eink, [0, 0], [0, 0]);
    var matte = shapeLayer(comp, "SCREEN_MATTE");
    rectGroup(root(matte), "matte", S.x, S.y, S.w, S.h, S.r, [1, 1, 1]);
    if (typeof eink.setTrackMatte === "function") {
        eink.setTrackMatte(matte, TrackMatteType.ALPHA);
    } else {
        eink.trackMatteType = TrackMatteType.ALPHA;   // legacy: uses the layer directly above
    }
    matte.enabled = false;

    if (variant === "audio") {
        var P = D.PROGRESS, G = D.PLAY, WV = D.WAVE;
        var prog = shapeLayer(comp, "PROGRESS");
        rectGroup(root(prog), "fill", P.x, P.y, P.w * P.fill, P.h, P.h / 2, D.C.INK_DARK);
        rectGroup(root(prog), "track", P.x, P.y, P.w, P.h, P.h / 2, D.C.TRACK);
        var play = shapeLayer(comp, "PLAY");
        var pg = root(play).addProperty("ADBE Vector Group");
        pg.name = "play";
        var pc = root(play).property("play").property("ADBE Vectors Group");
        var path = pc.addProperty("ADBE Vector Shape - Group");
        var tri = new Shape();
        tri.vertices = [[G.x, G.cy - G.h / 2], [G.x + G.w, G.cy], [G.x, G.cy + G.h / 2]];
        tri.closed = true;
        path.property("ADBE Vector Shape").setValue(tri);
        pc = root(play).property("play").property("ADBE Vectors Group");
        pc.addProperty("ADBE Vector Graphic - Fill").property("ADBE Vector Fill Color")
            .setValue([D.C.INK_DARK[0], D.C.INK_DARK[1], D.C.INK_DARK[2], 1]);
        var wave = shapeLayer(comp, "WAVEFORM");
        for (var j = 0; j < WV.peaks.length; j++) {
            var bx = WV.x + j * (WV.bar_w + WV.gap);
            var bar = rectGroup(root(wave), "bar_" + (j + 1), bx, WV.cy - WV.rest / 2, WV.bar_w, WV.rest,
                                WV.bar_w / 2, D.C.INK_DARK);
            // one beat after landing, then back to rest (only extra motion; ends well before 5 s)
            root(wave).property("bar_" + (j + 1)).property("ADBE Vectors Group").property(1)
                .property("ADBE Vector Rect Size").expression =
                "var u = (time - " + D.WAVE_T0 + " - " + (j * WV.stagger) + ") / " + WV.dur + ";\n" +
                "var b = (u > 0 && u < 1) ? Math.sin(Math.PI * u) : 0;\n" +
                "[" + WV.bar_w + ", " + WV.rest + " + " + (WV.peaks[j] - WV.rest) + " * b]";
        }
    }
    return comp;
}

var ebook = build("ebook");
build("audio");
ebook.openInViewer();
app.endUndoGroup();
alert("YIR26 carousel rig built: _CONTROLS, yir26-carousel-ebook, yir26-carousel-audio.\n" +
      "Brand swap = the three colour controls on _CONTROLS > CONTROLS.\nSave as yir26-carousel.aep.");
})();
